branch-defaults:
  master:
    environment: aws-test-env
    group_suffix: null
global:
  application_name: aws-test
  default_ec2_keyname: null
  default_platform: Ruby 2.1 (Puma)
  default_region: eu-central-1
  profile: eb-cli
  sc: git
